# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63fa191600f7dd7bee80dd8a2fccf428ac995b8e9d31f6b697e27d3a315748a4d59cc0114b246509aeca2a98b5d9823bdd9ea6b213f7932d25cef0232d6dfe62

test:
  secret_key_base: 6a74116b7014c2c65c1c7ab38be28b7b319034f4bfb6c7f21bcb25c02337c29818a42a475526f577b037af03cfd318b61aa7f6451b634287217f0591d62b9b41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
